[16.0][IMP] base_config_discount: Add check global discount in product
OCA/server-backend pull request #221
Opened 2023-06-22 06:42 UTC by Rferri44-S73

Add check global discount in products

2023-08-28 12:07 UTC, QuocDuong1306 approved these changes
lgtm

2023-08-31 06:24 UTC, cyrilmanuel approved these changes
LGTM

2023-09-01 13:11 UTC, rafaelbn commented
Hello! :-)

This module is base_global_discount and not base_config_discount

This should be reviewed by @ferran-S73 @rousseldenis or @pedrobaeza 

Thank you!

2023-09-04 06:09 UTC, ferran-S73 commented
Hi @rafaelbn since the original owner of the PR doesn't work here anymore I fixed the commit name myself. As for the changes in here LGTM

2023-09-04 06:09 UTC, ferran-S73 commented
I guess the title of the PR has to be changed by a maintainer

2023-10-09 11:41 UTC, simahawk requested changes
LG overall, just a quick code review tho.

TODO:

1. rollback module version
2. remove odoo version from commit

@pedrobaeza anyone from Tecnativa to review?

2023-10-09 11:41 UTC, simahawk commented on base_global_discount/__manifest__.py
> +    "version": "16.0.1.1.0",
module version will be changed by the bot

2023-10-09 11:50 UTC, pedrobaeza reviewed
I think in a business perspective more logical to use a negative flag: don't apply global discount, although the formula I prefer is to add a m2m in each global discount to exclude some products from them.

2023-10-09 11:50 UTC, pedrobaeza commented on base_global_discount/models/product_product.py
> +        required=True,
required in a boolean is a nonsense.

2023-10-18 11:17 UTC, ferran-S73 commented
@simahawk @pedrobaeza changes done, I haven't changed the field itself as to no disrupt our clients that are already using this feature

2023-10-18 11:25 UTC, pedrobaeza commented
Well, you can put migration scripts, but keeping weird fields in the definitive version is not desirable.

2023-10-18 14:18 UTC, simahawk commented
> Well, you can put migration scripts, but keeping weird fields in the definitive version is not desirable.

I agree. In this case you are allowed to change the version manually and add a pre/post migrate script to adapt existing installations.

2023-11-16 09:12 UTC, simahawk commented
@Rferri44-S73 ping

2023-11-16 09:53 UTC, ferran-S73 commented
> @Rferri44-S73 ping

Hi @simahawk , I'm sorry I haven't been able to update this pr as requested. I have this in my todo list and will eventually apply the suggestions you and @pedrobaeza gave me. Sorry for the inconvenience

2024-03-26 10:40 UTC, cyrilmanuel commented
Hi @ferran-S73  little ping have you the time to work on it  ? :)

2024-04-01 18:29 UTC, carolinafernandez-tecnativa commented
Hi, could you please rebase? Thanks!

2024-05-11 17:02 UTC, dreispt commented
This is blocking https://github.com/OCA/account-invoicing/pull/1338
What can be done to move forward?

2024-05-15 16:27 UTC, carolinafernandez-tecnativa approved these changes
LGTM, Thanks!

2024-05-15 16:30 UTC, carolinafernandez-tecnativa commented
@simahawk can we proceed to merge? this blocks https://github.com/OCA/account-invoicing/pull/1338

2024-05-17 07:01 UTC, pedrobaeza commented on base_global_discount/models/product_product.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```suggestion
# License AGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```

2024-05-17 07:01 UTC, pedrobaeza commented on base_global_discount/models/product_template.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```suggestion
# License AGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```

2024-05-17 07:36 UTC, pedrobaeza commented
Summarizing this one, apart from my latest comments, we are talking about not putting a flag in the product, that is very disrupting, but add a m2m in the global discounts for including or excluding. That way, you get even more granularity.

2024-05-20 15:31 UTC, ferran-S73 commented
Hi @pedrobaeza I'va update this PR adding a negative flag on the products as accorded on https://github.com/OCA/account-invoicing/pull/1725#issuecomment-2120503216

I have also updated th following PRs that depend on this one
- https://github.com/OCA/account-invoicing/pull/1725
- https://github.com/OCA/sale-workflow/pull/2343

Hope everything is alright now!

2024-05-23 17:24 UTC, pedrobaeza approved these changes
OK, I think it's good enough

/ocabot merge minor

2024-05-23 17:28 UTC, merged