[MIG] base_dav: Migration to 17.0
OCA/server-backend pull request #269
Opened 2024-02-14 16:33 UTC by jaydeep32

To install and use this module, use the right version of `radicale==2.1.12` python package.

2024-03-09 14:29 UTC, dreispt requested changes
I'm sorry, the commit history is missing.

2024-03-09 16:04 UTC, jaydeep32 commented
It is missing because this module is on v11, and in between form 12-16 versions this module was not migrated.

2024-03-09 16:35 UTC, dreispt commented
@jaydeep32 the migration should get the commits from the previous available version, 11.0 in that case, and then add changes to it. The commit history procedure is explained in the migration Issue of the repo. Just replace 16.0 with 11.0.

2024-03-18 22:27 UTC, jaydeep32 commented
Hi, @dreispt. Copying the commit from 11.0 and adding it to this branch is very complex for me, so is it okay if I make a new PR with an 11.0 history for this module, and then we can close this one?

2024-03-19 16:06 UTC, dreispt commented
@jaydeep32 Did you try the migration recipe, replacing 15.0 with 11.0?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

2024-03-19 17:43 UTC, jaydeep32 commented
Yes, I have, but like in my current branch if I make this, it makes many conflicts with new module changes, making it harder to resolve. However, it would work well if I created a new branch and then did this. So this is why I asked if I could make a new branch and PR.

2024-03-20 11:36 UTC, dreispt commented
@jaydeep32 Yes, you should use the recipe to create a new clean branch, and after that add your migration changes.
Let me know if you need help.

2024-03-20 14:23 UTC, jaydeep32 commented
Hello @dreispt Now is it ok? I have added those commits from 11.0 to this one.

2024-03-20 14:41 UTC, dreispt commented on base_dav/__manifest__.py
> +        "python": ["radicale==2.1.12"],
Can this be >= ?

2024-03-20 14:43 UTC, dreispt commented on base_dav/models/dav_collection.py
> +        self = self.with_user(SUPERUSER_ID)
This raises security concerns, why is this required?

2024-03-20 14:43 UTC, amh-mw requested changes
@jaydeep32 This doesn't look right. Why are there commits specific to the base_user_role_company module? I second @dreispt 's comment that you need to start fresh with a clean local folder and follow the steps in the migration documentation.

2024-03-20 14:45 UTC, dreispt commented
@jaydeep32 Great work, you made it!
Now I can see your migration changes.
I made a couple of questions, thanks.

2024-03-20 14:58 UTC, dreispt commented
@amh-mw You're right.
@jaydeep32 I ran the migration process myself and applied your changes, here https://github.com/OCA/server-backend/pull/276
This has the correct history.

I suggest you fetch my branch, `git reset` this branch to it, and continue from there.

2024-03-20 15:38 UTC, jaydeep32 commented on base_dav/__manifest__.py
> +        "python": ["radicale==2.1.12"],
Here, I use this specific module version because this module's code is only compatible with this 2.1.12 or older version of  `radical.` If you check this #254 issue here, @AquaMCU has mentioned that he is having this strange error in the log, 
so I solved that by changing the module version to `radicale==2.1.12.`

Also, if possible, can we add @AquaMCU to the discussion since he is the one who has migrated the module? 
Actually, he was not able to create PR, so I simply made that for him

2024-07-11 19:02 UTC, flotho requested changes
thanks for this PR.
I thinks some ACL are missing  for http://oca-server-backend-17-0-pr269-360893ee9167.runboat.odoo-community.org/web?debug=1#id=1&cids=1&menu_id=65&action=77&model=dav.collection&view_type=form
![image](https://github.com/OCA/server-backend/assets/1043935/3fa7520b-768e-4dfe-a31f-d8e56f5b56d0)

2024-07-11 19:27 UTC, flotho commented
> thanks for this PR. I thinks some ACL are missing for http://oca-server-backend-17-0-pr269-360893ee9167.runboat.odoo-community.org/web?debug=1#id=1&cids=1&menu_id=65&action=77&model=dav.collection&view_type=form ![image](https://private-user-images.githubusercontent.com/1043935/347957489-3fa7520b-768e-4dfe-a31f-d8e56f5b56d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjQ5MTcsIm5iZiI6MTcyMDcyNDYxNywicGF0aCI6Ii8xMDQzOTM1LzM0Nzk1NzQ4OS0zZmE3NTIwYi03NjhlLTRkZmUtYTMxZi1kOGU1NmY1YjU2ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTkwMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTdlNWFiODVmY2JhYmU4MjI0OTJkNDAwMGM3NGM5MGNkNmE4MTJkY2I1ODhmYjRjMDdmYjViM2Q0YzRkMzQyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jAj1ieM3Rt7eXqt1QTTm6Lv0F0quCvLhF5fqKy3f0gk)

mostly impossible to configure this in the UI

2024-07-29 10:44 UTC, eLBati commented
Should we move to https://github.com/OCA/server-backend/pull/276 ?

2024-10-05 08:55 UTC, josselex commented
Is there any progress on it? Maybe even upgrading it to Odoo 18? Can we sponsor this?

2025-03-09 12:15 UTC, closed without merging

2025-12-12 20:22 UTC, Katulos commented
> Is there any progress on it? Maybe even upgrading it to Odoo 18? Can we sponsor this?

Hello.
Porting to 18.0 is no problem. But as we see, OCA isn't accepting pull requests.

2026-03-06 17:32 UTC, Aldeigja commented
> Is there any progress on it? Maybe even upgrading it to Odoo 18? Can we sponsor this?

@josselex  Please take a look at https://github.com/OCA/server-backend/pull/431 functional testing and code review would be very helpful.