[17.0][MIG] base_external_dbsource_mssql: Migration to 17.0
OCA/server-backend pull request #298
Opened 2024-07-16 16:06 UTC by carolinafernandez-tecnativa

Standard migration to v17.

Depends on:

[ base_external_dbsource_sqlite] https://github.com/OCA/server-backend/pull/295

@Tecnativa
TT50002

@pedrobaeza @sergio-teruel

2024-07-25 10:28 UTC, carolinafernandez-tecnativa commented
ping @sergio-teruel @pedrobaeza

2024-07-25 10:32 UTC, pedrobaeza commented
/ocabot migration base_external_dbsource_mssql

2024-07-26 18:01 UTC, pedrobaeza requested changes

2024-07-26 18:01 UTC, pedrobaeza commented on base_external_dbsource_mssql/demo/base_external_dbsource.xml
> +        >mssql+pymssql://myUsername:%s@myServerAddress:port/myDataBase</field>
Is this the final connection string?

2024-07-26 18:01 UTC, pedrobaeza commented on base_external_dbsource_mssql/models/base_external_dbsource.py
>  import pymssql
If you don't do the import, isn't this working?

2024-07-26 18:01 UTC, pedrobaeza commented on base_external_dbsource_mssql/models/base_external_dbsource.py
> -# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
Why removing the license?

2024-07-26 18:01 UTC, pedrobaeza commented on base_external_dbsource_mssql/models/base_external_dbsource.py
> +        return sqlalchemy.create_engine(self.conn_string_full).connect()
Why not doing the computed connection string as talked?

2024-11-08 22:25 UTC, TheCloneMaster commented
I tried this and works fine

2024-11-08 22:28 UTC, pedrobaeza commented
@sergio-teruel can you resume this?

2024-11-09 16:02 UTC, TheCloneMaster commented
By "works fine" I mean it connects to the server, but upon closer inspection, it is half way there...
I will complete migration to pymssql and remove sqlalchemy requirement

2024-11-27 00:46 UTC, TheCloneMaster commented
I have this one completed, with sqlalchemy dependency removed, based totally on pymssql.
Also base_external_import (tested against MS Sql Server), where should I apply the PRs ?

Regards,
-Mario

2024-11-27 07:16 UTC, pedrobaeza commented
Do a new PR and we close this one.

2025-05-04 12:21 UTC, closed without merging